services:
  app:
    build:
      context: . 
      dockerfile: Dockerfile.dev
    volumes:
      - ./src/laravel-arya:/var/www/html
      - /var/www/html/vendor:/var/www/html/vendor
    working_dir: /var/www/html
    container_name: laravel_app
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
    networks:
      - laravel

  nginx:
    image: nginx:alpine # Menggunakan image nginx:latest dari Docker Hub
    ports:
      - "8000:80"
    volumes:
      - ./src/laravel-arya:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    container_name: laravel_nginx
    networks:
      - laravel

  node:
    build:
      context: .
      dockerfile: Dockerfile.node  # Gunakan Dockerfile khusus Node.js
    volumes:
      - ./src/laravel-arya:/var/www/html  # Volume untuk source code Laravel
      - ./src/laravel-arya/node_modules:/var/www/html/node_modules  
    working_dir: /var/www/html
    container_name: laravel_node
    networks:
      - laravel
    command: ["tail", "-f", "/dev/null"]


networks:
  laravel:
    driver: bridge